### ISSUE TITLE
Fresh Install Missing mysqli

### ISSUE THREAD

**Issue by PhilipHow** [ChurchCRM/Docker#16]
Hey,

I've tried a new install and I'm getting the following error:

PHP Fatal error:  Uncaught Error: Call to undefined function mysqli_connect()

Seems the image is missing msqli?

More here: https://github.com/ChurchCRM/CRM/issues/810

**Comment by rsnyman** [comment]
I'm getting this error too.

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php7/modules/apcu.so' - Error relocating /usr/lib/php7/modules/apcu.so: php_pcre_exec: symbol not found in Unknown on line 0
[Wed Apr 03 18:07:31.647839 2019] [mpm_prefork:notice] [pid 60] AH00163: Apache/2.4.29 (Unix) PHP/7.1.15 configured -- resuming normal operations
[Wed Apr 03 18:07:31.647867 2019] [core:notice] [pid 60] AH00094: Command line: '/usr/sbin/httpd -D NO_DETACH -f /web/config/httpd.conf'
[Wed Apr 03 18:07:34.636531 2019] [php7:error] [pid 65] [client 172.18.0.1:55018] PHP Fatal error:  Uncaught Error: Call to undefined function ChurchCRM\\mysqli_connect() in /web/html/ChurchCRM/Bootstrapper.php:140\nStack trace:\n#0 /web/html/ChurchCRM/Bootstrapper.php(64): ChurchCRM\\Bootstrapper::initMySQLI()\n#1 /web/html/Include/LoadConfigs.php(21): ChurchCRM\\Bootstrapper::init('database', '||DB_SERVER_POR...', 'churchcrm', 'churchcrm', 'churchcrm', '', false, Array)\n#2 /web/html/Include/Config.php(62): require_once('/web/html/Inclu...')\n#3 /web/html/index.php(8): require_once('/web/html/Inclu...')\n#4 {main}\n  thrown in /web/html/ChurchCRM/Bootstrapper.php on line 140
[Wed Apr 03 18:08:10.661964 2019] [php7:error] [pid 66] [client 172.18.0.1:55078] PHP Fatal error:  Uncaught Error: Call to undefined function ChurchCRM\\mysqli_connect() in /web/html/ChurchCRM/Bootstrapper.php:140\nStack trace:\n#0 /web/html/ChurchCRM/Bootstrapper.php(64): ChurchCRM\\Bootstrapper::initMySQLI()\n#1 /web/html/Include/LoadConfigs.php(21): ChurchCRM\\Bootstrapper::init('database', '||DB_SERVER_POR...', 'churchcrm', 'churchcrm', 'churchcrm', '', false, Array)\n#2 /web/html/Include/Config.php(62): require_once('/web/html/Inclu...')\n#3 /web/html/index.php(8): require_once('/web/html/Inclu...')\n#4 {main}\n  thrown in /web/html/ChurchCRM/Bootstrapper.php on line 140
[Wed Apr 03 18:08:46.875323 2019] [php7:error] [pid 67] [client 172.18.0.1:55100] PHP Fatal error:  Uncaught Error: Call to undefined function ChurchCRM\\mysqli_connect() in /web/html/ChurchCRM/Bootstrapper.php:140\nStack trace:\n#0 /web/html/ChurchCRM/Bootstrapper.php(64): ChurchCRM\\Bootstrapper::initMySQLI()\n#1 /web/html/Include/LoadConfigs.php(21): ChurchCRM\\Bootstrapper::init('database', '||DB_SERVER_POR...', 'churchcrm', 'churchcrm', 'churchcrm', '', false, Array)\n#2 /web/html/Include/Config.php(62): require_once('/web/html/Inclu...')\n#3 /web/html/index.php(8): require_once('/web/html/Inclu...')\n#4 {main}\n  thrown in /web/html/ChurchCRM/Bootstrapper.php on line 140
```
